Header
LouisBruge/lesjoiesdelawild pull request #1
Opened 2018-03-06 17:23 UTC by Dine16

add header.php

2018-03-06 17:28 UTC, LouisBruge commented
Can you add the collapse feature of the library Bootstrap

2018-03-06 17:35 UTC, Dine16 commented
add the burger menu code

2018-03-06 21:20 UTC, LouisBruge requested changes
Some modifications before to merge your work

2018-03-06 21:20 UTC, LouisBruge commented on src/html/header.php
> +
Remove this line. It's useless. 
It will be write into the main pages

2018-03-06 21:20 UTC, LouisBruge commented on src/html/header.php
> +                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" id="bs-example-navbar-collapse-1 aria-expanded="false">
please, change the
```html
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" id="bs-example-navbar-collapse-1 aria-expanded="false">
```
into a
```html
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar" aria-expanded="false">
```

2018-03-06 21:20 UTC, LouisBruge commented on src/html/header.php
>                      <ul class="nav navbar-nav navbar-right">
before the 
```html
<ul class="nav navbar-nav navbar-right">
```
can you add a div tag : 
```html
<div class="collapse navbar-collapse" id="top-navbar">
```

and close the tag, between the lines 26 and 27, with a close </div> tag

2018-03-06 22:07 UTC, Dine16 commented
add footer.php

2018-03-07 08:31 UTC, Dine16 commented
just made the modifications needed!

2018-03-07 08:43 UTC, merged